version: '3'

services:
  database:
    image: mongo
    container_name: database
    restart: unless-stopped
    volumes:
      - mongo:/data/db
    networks:
      - app-network
  #Needs node specific environment variables
  nodejs:
    build: .
    container_name: nodejs
    restart: unless-stopped
    ports: 
      - "80:3000"
    networks:
      - app-network
    depends_on:
      - database
volumes:
  mongo:
networks:
  app-network: